# Generated by Django 4.0.6 on 2022-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.URLField()),
                ('content', models.TextField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Posts',
            },
        ),
    ]
